export type PermissionKey =
  | "accessDashboard"
  | "viewUsers"
  | "manageUsers"
  | "manageRoles"
  | "manageSettings"
  | "accessSettingsPage"
  | "manageEmailProviders"
  | "manageDesigns"
  | "viewDesigns"
  | "createDesigns"
  | "editDesigns"
  | "archiveDesigns"
  | "restoreDesigns"
  | "manageCategories"
  | "importDesigns"
  | "manageQueues"
  | "viewPrintRequests"
  | "managePrintRequests"
  | "managePrintRequestItems"
  | "viewUpcomingShows"
  | "manageUpcomingShows"
  | "manageShowQueueSettings"
  | "importWhatnotShows"
  | "createStaffGangSheetLane"
  | "manageStaffGangSheetLane"
  | "openDevTools"
  | "manageGuestCustomers"
  | "manageCustomers"
  | "manageRequests"
  | "viewAuditLogs"
  | "viewOriginals"
  | "viewAiReview"
  | "manageAiReview"
  | "wipeOperationalTestData"
  | "purgeArchivedDesignAssets"
  | "deleteEligibleUnapprovedDesigns"
  | "submitCustomerRequests"
  | "viewOwnCustomerRequests";

export interface PermissionContext {
  customerId?: string;
}
