import { app, BrowserWindow, Menu, screen, type BrowserWindowConstructorOptions, type Rectangle } from 'electron'
import { existsSync, readFileSync, writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import path from 'node:path'

import { suppressDevToolsAutofillConsoleNoise } from './dev/suppressDevToolsAutofillConsoleNoise'
import { registerAppIpcHandlers } from './ipc/app/appIpcHandlers'
import { APP_CONFIRM_CLOSE_REQUESTED } from './ipc/app/appIpcChannels'
import { attachDevToolsWindowPersistence } from './ipc/app/devToolsWindowState'
import { openExternalLinkOnSameDisplay } from './ipc/app/externalLinkWindow'
import { applyStudioWindowMinimumSize } from './ipc/app/windowMetrics'
import { consumeCloseConfirmation, getUploadActive } from './ipc/app/uploadActivityState'
import {
  STUDIO_MIN_WINDOW_HEIGHT,
  STUDIO_MIN_WINDOW_WIDTH,
} from './window/studioWindowConstraints'
import {
  closeFirebaseDebugWindow,
  registerFirebaseDebugIpcHandlers,
} from './ipc/firebaseDebug/firebaseDebugIpcHandlers'
import { registerAiQueueTraceIpcHandlers } from './ipc/aiQueueTrace/aiQueueTraceIpcHandlers'
import { registerExportIpcHandlers } from './ipc/export/exportIpcHandlers'
import { registerImportIpcHandlers } from './ipc/import/importIpcHandlers'
import { registerInboxAlertIpcHandlers } from './ipc/inboxAlert/inboxAlertIpcHandlers'
import { registerWhatnotImportIpcHandlers } from './ipc/whatnotImport/whatnotImportIpcHandlers'
import { registerStudioUpdateIpcHandlers } from './ipc/studioUpdate/studioUpdateIpcHandlers'
import { registerTaxonomyCacheIpcHandlers } from './ipc/taxonomyCache/taxonomyCacheIpcHandlers'
import { startPeriodicStudioUpdateChecks } from './ipc/studioUpdate/studioUpdateService'
import { attachTextInputContextMenu } from './services/app/textInputContextMenu'

suppressDevToolsAutofillConsoleNoise()

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const appName = 'Fresh Prints Desktop'
// Only meaningful in dev mode / on Linux — on packaged Windows/macOS the OS reads the icon
// embedded in the executable at build time (electron-builder's win.icon/mac.icon via rcedit),
// not this runtime option. See apps/studio/icon.ico / apps/studio/icon.png (generated by
// apps/studio/scripts/generate-app-icon.mjs) for the packaged icon.
const appIconFileName = 'app-icon.png'

// The built directory structure
//
// ├─┬─┬ dist
// │ │ └── index.html
// │ │
// │ ├─┬ dist-electron
// │ │ ├── main.js
// │ │ └── preload.mjs
// │
process.env.APP_ROOT = path.join(__dirname, '..')

// 🚧 Use ['ENV_NAME'] avoid vite:define plugin - Vite@2.x
export const VITE_DEV_SERVER_URL = process.env['VITE_DEV_SERVER_URL']
export const MAIN_DIST = path.join(process.env.APP_ROOT, 'dist-electron')
export const RENDERER_DIST = path.join(process.env.APP_ROOT, 'dist')

process.env.VITE_PUBLIC = VITE_DEV_SERVER_URL ? path.join(process.env.APP_ROOT, 'public') : RENDERER_DIST

let win: BrowserWindow | null
let saveWindowStateTimeout: ReturnType<typeof setTimeout> | null = null

interface SavedWindowState {
  bounds: Rectangle
  displayId?: number
  isMaximized: boolean
}

function getWindowStatePath() {
  return path.join(app.getPath('userData'), 'window-state.json')
}

function clampBoundsToWorkArea(bounds: Rectangle, workArea: Rectangle): Rectangle {
  const width = Math.min(bounds.width, workArea.width)
  const height = Math.min(bounds.height, workArea.height)
  const x = Math.max(workArea.x, Math.min(bounds.x, workArea.x + workArea.width - width))
  const y = Math.max(workArea.y, Math.min(bounds.y, workArea.y + workArea.height - height))

  return { x, y, width, height }
}

function getDisplayById(displayId: number) {
  return screen.getAllDisplays().find((display) => display.id === displayId)
}

function normalizeSavedWindowBounds(
  rawBounds: Partial<Rectangle>,
  displayId?: number,
): Rectangle | null {
  if (typeof rawBounds.x !== 'number' || typeof rawBounds.y !== 'number') {
    return null
  }

  const width = Math.max(
    typeof rawBounds.width === 'number' && Number.isFinite(rawBounds.width)
      ? rawBounds.width
      : STUDIO_MIN_WINDOW_WIDTH,
    STUDIO_MIN_WINDOW_WIDTH,
  )
  const height = Math.max(
    typeof rawBounds.height === 'number' && Number.isFinite(rawBounds.height)
      ? rawBounds.height
      : STUDIO_MIN_WINDOW_HEIGHT,
    STUDIO_MIN_WINDOW_HEIGHT,
  )

  const savedDisplay = displayId !== undefined ? getDisplayById(displayId) : undefined
  const targetDisplay =
    savedDisplay ?? screen.getDisplayMatching({ x: rawBounds.x, y: rawBounds.y, width: 1, height: 1 })
  const normalized = clampBoundsToWorkArea(
    { x: rawBounds.x, y: rawBounds.y, width, height },
    targetDisplay.workArea,
  )

  if (!isVisibleOnAnyDisplay(normalized)) {
    return null
  }

  return normalized
}

function rectanglesIntersect(first: Rectangle, second: Rectangle) {
  return (
    first.x < second.x + second.width &&
    first.x + first.width > second.x &&
    first.y < second.y + second.height &&
    first.y + first.height > second.y
  )
}

function isVisibleOnAnyDisplay(bounds: Rectangle) {
  return screen.getAllDisplays().some((display) => rectanglesIntersect(bounds, display.workArea))
}

function getCenteredPrimaryDisplayBounds(): Rectangle {
  const { workArea } = screen.getPrimaryDisplay()
  const width = Math.min(STUDIO_MIN_WINDOW_WIDTH, workArea.width)
  const height = Math.min(STUDIO_MIN_WINDOW_HEIGHT, workArea.height)

  return clampBoundsToWorkArea(
    {
      x: Math.round(workArea.x + (workArea.width - width) / 2),
      y: Math.round(workArea.y + (workArea.height - height) / 2),
      width,
      height,
    },
    workArea,
  )
}

function loadWindowState(): SavedWindowState {
  const fallbackState: SavedWindowState = {
    bounds: getCenteredPrimaryDisplayBounds(),
    isMaximized: false,
  }

  try {
    const windowStatePath = getWindowStatePath()

    if (!existsSync(windowStatePath)) {
      return fallbackState
    }

    const parsedState: unknown = JSON.parse(readFileSync(windowStatePath, 'utf-8'))

    if (!parsedState || typeof parsedState !== 'object') {
      return fallbackState
    }

    const rawState = parsedState as Partial<SavedWindowState>
    const normalizedBounds = normalizeSavedWindowBounds(
      (rawState.bounds ?? {}) as Partial<Rectangle>,
      rawState.displayId,
    )

    if (!normalizedBounds) {
      return fallbackState
    }

    return {
      bounds: normalizedBounds,
      displayId: rawState.displayId,
      isMaximized: typeof rawState.isMaximized === 'boolean' ? rawState.isMaximized : false,
    }
  } catch {
    return fallbackState
  }
}

function saveWindowState(browserWindow: BrowserWindow) {
  if (browserWindow.isDestroyed()) {
    return
  }

  const bounds = browserWindow.getNormalBounds()
  const display = screen.getDisplayMatching(bounds)
  const windowState: SavedWindowState = {
    bounds,
    displayId: display.id,
    isMaximized: browserWindow.isMaximized(),
  }

  try {
    writeFileSync(getWindowStatePath(), JSON.stringify(windowState, null, 2))
  } catch {
    // Window placement persistence should not prevent the app from closing.
  }
}

function scheduleWindowStateSave(browserWindow: BrowserWindow) {
  if (saveWindowStateTimeout) {
    clearTimeout(saveWindowStateTimeout)
  }

  saveWindowStateTimeout = setTimeout(() => {
    saveWindowState(browserWindow)
    saveWindowStateTimeout = null
  }, 300)
}

function createWindow() {
  const savedWindowState = loadWindowState()
  const windowOptions: BrowserWindowConstructorOptions = {
    ...savedWindowState.bounds,
    icon: path.join(process.env.VITE_PUBLIC ?? RENDERER_DIST, appIconFileName),
    title: appName,
    webPreferences: {
      contextIsolation: true,
      nodeIntegration: false,
      preload: path.join(__dirname, 'preload.mjs'),
    },
  }

  win = new BrowserWindow({
    ...windowOptions,
  })

  applyStudioWindowMinimumSize(win)

  if (savedWindowState.isMaximized) {
    win.maximize()
  }

  win.on('resize', () => scheduleWindowStateSave(win as BrowserWindow))
  win.on('move', () => scheduleWindowStateSave(win as BrowserWindow))
  win.on('closed', () => {
    closeFirebaseDebugWindow()
    win = null
  })
  win.on('close', (event) => {
    // Window bounds persistence must keep firing on every close attempt regardless of whether the
    // close is later blocked/confirmed by the upload guard below.
    saveWindowState(win as BrowserWindow)

    if (consumeCloseConfirmation()) {
      return
    }

    if (!getUploadActive()) {
      closeFirebaseDebugWindow()
      return
    }

    event.preventDefault()
    win?.webContents.send(APP_CONFIRM_CLOSE_REQUESTED)
  })

  if (!app.isPackaged) {
    attachDevToolsWindowPersistence(win.webContents)
  }

  attachTextInputContextMenu(win.webContents)

  // Keep window.open / target=_blank on the same monitor as Studio (OS browser placement cannot).
  win.webContents.setWindowOpenHandler(({ url }) => {
    openExternalLinkOnSameDisplay(url, win)
    return { action: 'deny' }
  })

  if (VITE_DEV_SERVER_URL) {
    win.loadURL(VITE_DEV_SERVER_URL)
  } else {
    // win.loadFile('dist/index.html')
    win.loadFile(path.join(RENDERER_DIST, 'index.html'))
  }
}

// Quit when all windows are closed, except on macOS. There, it's common
// for applications and their menu bar to stay active until the user quits
// explicitly with Cmd + Q.
app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') {
    app.quit()
    win = null
  }
})

app.on('activate', () => {
  // On OS X it's common to re-create a window in the app when the
  // dock icon is clicked and there are no other windows open.
  if (BrowserWindow.getAllWindows().length === 0) {
    createWindow()
  }
})

app.whenReady().then(() => {
  app.setName(appName)
  Menu.setApplicationMenu(null)
  registerAppIpcHandlers()
  registerFirebaseDebugIpcHandlers({
    getMainWindow: () => win,
    getPreloadPath: () => path.join(__dirname, 'preload.mjs'),
    getRendererDist: () => RENDERER_DIST,
    getDevServerUrl: () => VITE_DEV_SERVER_URL,
    isPackaged: () => app.isPackaged,
  })
  registerAiQueueTraceIpcHandlers({
    isPackaged: () => app.isPackaged,
  })
  registerImportIpcHandlers()
  registerInboxAlertIpcHandlers()
  registerWhatnotImportIpcHandlers()
  registerExportIpcHandlers()
  registerStudioUpdateIpcHandlers()
  registerTaxonomyCacheIpcHandlers()

  createWindow()

  // Update checks run only in packaged builds (see isUpdateCapable in studioUpdateService) —
  // this call is a no-op during `npm run dev:studio`.
  startPeriodicStudioUpdateChecks()
})
